### ISSUE TITLE
Antiquated Branches

### ISSUE THREAD

**Issue by adrianosorio** [SmartAsphalt159/smart_asphalt#20]
It seems their are three main branches that need to be closed that havent had use in months and appear to not have up to date code. Those branches mentioned being the lidar_update, controls_update, and andrew_dev. Please take time and ensure these branches are good to delete if no longer necessary. @caymanbarber @Akettle44

**Comment by Akettle44** [comment]
Andrew_dev has been removed

**Comment by adrianosorio** [comment]
Cayman Deleted unnnecessary branches.
